name: CI/CD

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Test
        run: npm test

      - name: Build
        run: npm run build
        
      - name: “Deployed site” 
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/67146caf08647761fcb79893

      
